### ISSUE TITLE
panic when disable and enable network card

### ISSUE THREAD

**Issue by tsxiaofang** [krojew/rust-zookeeper#7]
src/io.rs 
            let conn_resp = match ConnectResponse::read_from(&mut data) {
                Ok(conn_resp) => conn_resp,
                Err(e) => {
221               panic!("Failed to parse ConnectResponse {:?}", e);
                    // self.reconnect();
                    // return
                }
            };

**Comment by krojew** [comment]
Can you confirm the latest master works?
